### ISSUE TITLE
Cannot run with Jest

### ISSUE THREAD

**Issue by evanjmg** [thegamenicorus/react-native-phone-input#22]
FAIL  artifacts/index.ios.spec.js
  ● Test suite failed to run

    SyntaxError: Unexpected token / in JSON at position 38
        at Object.parse (native)
      
      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:325:61)
      at Object.<anonymous> (node_modules/react-native-phone-input/lib/phoneNumber.js:3:17)
      at Object.<anonymous> (node_modules/react-native-phone-input/lib/index.js:15:18)

**Comment by nating** [comment]
Glad to see the fix 👍- Any chance it could be released to npm?

**Comment by thegamenicorus** [comment]
released on npm 0.2.0. sorry for my delay.
