### ISSUE TITLE
error: bundling failed: Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by wzup** [thegamenicorus/react-native-phone-input#62]
Your `react-native-country-picker-modal` breaks whole application

```
import PhoneInput from 'react-native-phone-input';
import CountryPicker from 'react-native-country-picker-modal';
```

And you get
```
error: bundling failed: Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at Object.readSync (/Users/user/app/node_modules/graceful-fs/polyfills.js:138:28)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at Module._readSourceCode (/Users/user/app/node_modules/metro/src/node-haste/Module.js:206:29)
    at Module._getCacheProps (/Users/user/app/node_modules/metro/src/node-haste/Module.js:398:29)
    at Module._readFromTransformCache (/Users/user/app/node_modules/metro/src/node-haste/Module.js:359:29)
    at Module.readCached (/Users/user/app/node_modules/metro/src/node-haste/Module.js:346:19)
    at /Users/user/app/node_modules/metro/src/node-haste/Module.js:327:29
    at Generator.next (<anonymous>)
```

**Comment by Nagibaba** [comment]
It looks like there is a file not imported correctly. Kill all processes from port `8081`, then `react-native start –reset-cache`. You will see the issue on emulator

**Comment by sharma555** [comment]
Hi, 

when i m trying to read file by fs.readFileSync so i m getting error like this.which i mentioned below.can anyone let me know ? .how can fix error?

Error: EISDIR: illegal operation on a directory, read
at Object.fs.readSync (fs.js:675:18)
at tryReadSync (fs.js:540:20)
at Object.fs.readFileSync (fs.js:583:19)
at app.post (/home/vcap/app/server.js:1225:4)
at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
at next (/home/vcap/app/node_modules/express/lib/router/route.js:137:13)
at Immediate._onImmediate (/home/vcap/app/node_modules/multer/lib/make-middleware.js:53:37)
at runCallback (timers.js:814:20)
at tryOnImmediate (timers.js:768:5)
at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by jaydenwindle** [comment]
I agree with @Nagibaba - it looks like it may be an issue with your local environment, not necessarily an issue with this package.

@wzup I'm going to close this issue for now, but I'm happy to reopen it if you'd like to provide some more information so that we can track down the issue :)
